export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const MAIN = '/'
export const TYPE_ROUTE = '/types'
export const SPEC_ROUTE = '/spec'
export const GRAPH = '/graph'